# Generated by Django 3.1 on 2020-08-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('idade', models.IntegerField(default=0)),
                ('data_de_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('apelido', models.CharField(max_length=100)),
                ('obs', models.TextField(max_length=400)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
